version: '3.4'

services:
  webapimexc:
    image: ${DOCKER_REGISTRY-}webapimexc
    restart: always
    build:
      context: .
      dockerfile: WebApiMEXC/Dockerfile
      
    ports: 
      - "8080:8080"   
